import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  useQuery,
  gql
} from "@apollo/client";
import inf from '../imageSpacexapi.svg'


export default function Home({ launches }) {

console.log('launches', launches)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        List of Falcon 9 launches
        </h1>

        <p className={styles.description}>
        Data from the SpaceX API in Next.js with Apollo GraphQL.
        </p>

        <div className={styles.grid}>
        {launches.map(launch => {
            return (
            <a key={launch.id} href={launch.links.wikipedia} className={styles.card}>
            
            {/* check if image available with ternary operator */}
            {launch.links.flickr_images[0] ? (<Image src={launch.links.flickr_images[0]}
                    alt={launch.mission_name}
                    width="230"
                    height="230"
                    allow='autoplay; encrypted-media'
                /> ): (<Image src={inf}
                  alt={launch.mission_name}
                  width="230"
                  height="230"
                  allow='autoplay; encrypted-media'
              /> )}
            
            <h2>{launch.mission_name}</h2>
            <p><b>Mission name:</b> {launch.mission_name}</p>
            <p><b>Rocket used:</b> {launch.rocket.rocket_name}</p>
            <p><b>Launch success:</b> {launch.launch_success?"Yes":"No"}</p>
            <p><b>Launch date:</b> { new Date(launch.launch_date_local).toLocaleDateString("en-GB") }</p>
          </a>
            )
            
          })}
      
          

         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://api.spacex.land/graphql/',
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 10) {
          id
          mission_name
          mission_id
          launch_success
          launch_year
          launch_date_local
        
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
            wikipedia
            flickr_images
          }
          rocket {
            rocket_name
          }
        }
      }
    `
  });

// console.log('data', data)

return {
  props: {
    launches: data.launchesPast
  }
}
}